// app/layout.js
export const metadata = {
  title: 'Pipeline Automations',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
